---
title: "03.2.1_multi_algorith_feature_sel"
author: "Puvvula"
date: "2023-03-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(gglasso)
library(grpreg)
library(sparsegl)
library(Matrix)
library(tidyverse)
```


```{r}
var_selec <- function(X, y, group) {
  # Group graphical Lasso
  gr_cv <- cv.gglasso(X, y, group=group, loss="ls", pred.loss="L2",  nfolds=5)
  gr_min_beta <- coef(gr_cv, s = gr_cv$lambda.min)[-1]
  
  # Group Lasso
  grpp_cv <- cv.grpreg(X, y, group = group, penalty="grLasso",seed=5678,nfolds = 5)
  grpp_min_beta <- coef(grpp_cv, s = grpp_cv$lambda.min)[-1]
  
  #Sparse lasso
  sparse_cv<- cv.sparsegl(X, y, group = group, family = "gaussian", nfolds = 4)
  sparse_min_beta<- coef(sparse_cv, s= sparse_cv$lambda.min)[-1]
  
  # Return results as data frame
  return(as.data.frame(list(gr_lasso = gr_min_beta, grpp_lasso = grpp_min_beta,
                            sparse_lasso = sparse_min_beta)))
}
```



```{r}
var_selec <- function(X, Y, group) {
  results <- list()
  for (i in 1:3) {
    y <- Y[, i]
    # Group graphical Lasso
    gr_cv <- cv.gglasso(X, y, group=group, loss="ls", pred.loss="L2",  nfolds=5)
    gr_min_beta <- coef(gr_cv, s = gr_cv$lambda.min)[-1]
  
    # Group Lasso
    grpp_cv <- cv.grpreg(X, y, group = group, penalty="grLasso",seed=5678,nfolds = 5)
    grpp_min_beta <- coef(grpp_cv, s = grpp_cv$lambda.min)[-1]
  
    #Sparse lasso
    sparse_cv<- cv.sparsegl(X, y, group = group, family = "gaussian", nfolds = 4)
    sparse_min_beta<- coef(sparse_cv, s= sparse_cv$lambda.min)[-1]
  
    # Store results in list
    results[[paste0("outcome", i)]] <- as.data.frame(list(gr_lasso = gr_min_beta, 
                                                          grpp_lasso = grpp_min_beta,
                                                          sparse_lasso = sparse_min_beta))
  }
  # Return list of results
  return(results)
}


library(MASS)

# Set seed for reproducibility
set.seed(123)

# Simulate predictor matrix
n <- 100
p <- 10
X <- mvrnorm(n, mu = rep(0, p), Sigma = diag(p))

# Simulate outcome matrix
Y <- matrix(0, nrow = n, ncol = 3)
Y[, 1] <- X[, 1] + X[, 2] + rnorm(n)
Y[, 2] <- X[, 3] + X[, 4] + rnorm(n)
Y[, 3] <- X[, 5] + X[, 6] + rnorm(n)

# Set group membership of predictors
group <- rep(1:2, each = 5)

# Test the var_selec function
results <- var_selec(X, Y, group)

```

