---
title: "03.01_summary_plt"
author: "Puvvula"
date: "2023-02-17"
output: pdf_document
---

```{r, echo=FALSE, message=FALSE}

library(pacman)
pacman::p_load(tidyverse, janitor, cowplot)
path <- "E:/BBK17/pj/data_2023apr/obs_w_outcome/"

dat<- read_csv(paste0(path, "wppsi_f_analy.csv")) |> drop_na()
```

#preliminary data
```{r, echo=FALSE, message=FALSE}
dt<-read_csv("E:/BBK17/pj/wppsi_results/summary_plt.csv") |>
  mutate_if(is.character, as.factor) |>
  mutate(pct_imputed = if_else(pct_impu <25, "low", "high"))|>
  mutate(dum_var=1)
```

#final IQ dataset for publication
```{r}
dt<- dat |>
  mutate_if(is.numeric, round, 4) |>
  clean_names() |>
  rename(sigma_DEHP=dehp, di_Ethyl_OP=op_de, di_Methyl_OP=op_dm, city=center,
         mom_edu_cat=edu3)|>
  rename_at(vars(4:33, 43:45), toupper) |>
  mutate(cohort = ifelse(cohort == "1", "HOME", "MIREC")) |>
  select(1,2, 4:32, 43:45) |>
  pivot_longer(cols = -c(1,2), names_to = "measure", values_to = "value") 

#plot formatting
# Generate summary table by cohort level
summary_by_cohort <- dt |>
  group_by(measure, cohort) |>
  summarise(
    median = median(value),
    q25 = quantile(value, 0.25),
    q75 = quantile(value, 0.75)) |>
  mutate(across(where(is.numeric), ~ if_else(measure == "PB" & cohort == "HOME", . * 10, .)))

# Generate summary table for all levels combined
summary_combined <- dt |>
  group_by(measure) |>
  summarise(
    median = median(value),
    q25 = quantile(value, 0.25),
    q75 = quantile(value, 0.75),
    cohort = "Pooled")

# Combine both summary tables
st <- bind_rows(summary_by_cohort, summary_combined) 
```

#add % below LOD to st table
```{r}
bel_lod<- read_csv("E:/BBK17/pj/data_2023apr/lod_summaries.csv") |>
  mutate(pct_lod = str_extract(freq_pct, "\\((.*?)\\)")) |>
  mutate(pct_lod = str_remove_all(pct_lod, "\\(|\\)")) |>
  mutate(measure = toupper(chemical)) |>
  filter(is.na(rm)) |>
  mutate(pct_lod = as.numeric(pct_lod))

  
#NEED TO BE JOINED
st<- st |> left_join(bel_lod, by=c("measure", "cohort"))
```



define groups
```{r, echo=FALSE, message=FALSE}
group_dict <- list(
  "Outcome" = c("WPPSI_FSIQ", "WPPSI_PIQ", "WPPSI_VIQ"),
  "Metals" = c("PB", "HG", "DMA"),
  "POPs" = c("DDE", "PBDE47", "PCB118", "PCB138", "PCB153", "PCB180"),
  "PFAS" = c("PFHXS", "PFOA", "PFOS"),
  "OPFR" = c("BCETP","BDCPP", "DBUP", "DPHP"),
  "Parabens" = c("B_PB", "M_PB", "P_PB"),
  "TCS_BPA" = c("BPA", "TCS"),
  "Phthalates" = c("MBP", "MBZP", "MCPP", "SIGMA_DEHP", "MEP", "MIBP"),
  "OP_pest" = c("DI_ETHYL_OP", "DI_METHYL_OP")
)

# loop through the categories and assign them to groups
st$group <- NA_character_
for (i in seq_along(dt$measure)) {
  for (j in names(group_dict)) {
    if (st$measure[i] %in% group_dict[[j]]) {
      st$group[i] <- j
    }
  }
}
```


pops
```{r, echo=FALSE, message=FALSE}
dt_pops<- st |> filter(group=="POPs")

pops_mean <- dt_pops |> 
  group_by(measure) |> 
  summarize(mean_val = mean(median))

pops<-ggplot(dt_pops, aes(y = as.factor(cohort), x = median, xmin = q25, xmax = q75)) + 
  geom_pointrange(aes(col = cohort), position=position_dodge(width=1),size = 1) +
    scale_color_manual(values = c("HOME" = "#0072B2", 
                                  "MIREC" = "#D55E00", "Pooled" = "#000000"))+
    ylab("") +
    ggtitle("")+
    xlab("")+
    theme_bw()+
    theme(panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(colour = "black"),
          axis.line.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          legend.position="none",
          strip.text.x=element_text(size=10,angle=0),
          strip.placement = "top",
          strip.background = element_rect(fill="transparent", 
                                          colour = "transparent"))+
  facet_wrap(measure ~ ., scales = "free")
```

metal
```{r, echo=FALSE, message=FALSE}
dt_metal<- st |> filter(group=="Metals")

metal_mean <- dt_metal |> 
  group_by(measure) |> 
  summarize(mean_val = mean(median))

metal<-ggplot(dt_metal, aes(y = as.factor(cohort), x = median, xmin = q25, xmax = q75)) + 
  geom_pointrange(aes(col = cohort), position=position_dodge(width=1),size = 1) +
    scale_color_manual(values = c("HOME" = "#0072B2", 
                                  "MIREC" = "#D55E00", "Pooled" = "#000000"))+
    ylab("") +
    ggtitle("")+
    xlab("")+
    theme_bw()+
    theme(panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(colour = "black"),
          axis.line.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          legend.position="none",
          strip.text.x=element_text(size=10,angle=0),
          strip.placement = "top",
          strip.background = element_rect(fill="transparent", 
                                          colour = "transparent"))+
  facet_wrap(measure ~ ., scales = "free")
```

pfas
```{r, echo=FALSE, message=FALSE}
dt_pfas<- st |> filter(group=="PFAS")

pfas_mean <- dt_pfas |> 
  group_by(measure) |> 
  summarize(mean_val = mean(median))

pfas<-ggplot(dt_pfas, aes(y = as.factor(cohort), x = median, xmin = q25, xmax = q75)) + 
  geom_pointrange(aes(col = cohort), position=position_dodge(width=1),size = 1) +
    scale_color_manual(values = c("HOME" = "#0072B2", 
                                  "MIREC" = "#D55E00", "Pooled" = "#000000"))+
    ylab("") +
    ggtitle("")+
    xlab("")+
    theme_bw()+
    theme(panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(colour = "black"),
          axis.line.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          legend.position="none",
          strip.text.x=element_text(size=10,angle=0),
          strip.placement = "top",
          strip.background = element_rect(fill="transparent", 
                                          colour = "transparent"))+
  facet_wrap(measure ~ ., scales = "free")
```

opfr
```{r, echo=FALSE, message=FALSE}
dt_opfr<- st |> filter(group=="OPFR")

opfr_mean <- dt_opfr |> 
  group_by(measure) |> 
  summarize(mean_val = mean(median))

opfr<-ggplot(dt_opfr, aes(y = as.factor(cohort), x = median, xmin = q25, xmax = q75)) + 
  geom_pointrange(aes(col = cohort), position=position_dodge(width=1),size = 1) +
    scale_color_manual(values = c("HOME" = "#0072B2", 
                                  "MIREC" = "#D55E00", "Pooled" = "#000000"))+
    ylab("") +
    ggtitle("")+
    xlab("")+
    theme_bw()+
    theme(panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(colour = "black"),
          axis.line.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          legend.position="none",
          strip.text.x=element_text(size=10,angle=0),
          strip.placement = "top",
          strip.background = element_rect(fill="transparent", 
                                          colour = "transparent"))+
  facet_wrap(measure ~ ., scales = "free")
```

paraben
```{r, echo=FALSE, message=FALSE}
dt_paraben<- st |> filter(group=="Parabens")

paraben_mean <- dt_paraben |> 
  group_by(measure) |> 
  summarize(mean_val = mean(median))

paraben<-ggplot(dt_paraben, aes(y = as.factor(cohort), x = median, xmin = q25, xmax = q75))+ 
  geom_pointrange(aes(col = cohort), position=position_dodge(width=1),size = 1) +
    scale_color_manual(values = c("HOME" = "#0072B2", 
                                  "MIREC" = "#D55E00", "Pooled" = "#000000"))+
    ylab("") +
    ggtitle("")+
    xlab("")+
    theme_bw()+
    theme(panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(colour = "black"),
          axis.line.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          legend.position="none",
          strip.text.x=element_text(size=10,angle=0),
          strip.placement = "top",
          strip.background = element_rect(fill="transparent", 
                                          colour = "transparent"))+
  facet_wrap(measure ~ ., scales = "free")
```

tcs_bpa
```{r, echo=FALSE, message=FALSE}
dt_tcs_bpa<- st |> filter(group=="TCS_BPA")

tcs_bpa_mean <- dt_tcs_bpa |> 
  group_by(measure) |> 
  summarize(mean_val = mean(median))

tcs_bpa<-ggplot(dt_tcs_bpa, aes(y = as.factor(cohort), x = median, xmin = q25, xmax = q75)) + 
  geom_pointrange(aes(col = cohort), position=position_dodge(width=1),size = 1) +
    scale_color_manual(values = c("HOME" = "#0072B2", 
                                  "MIREC" = "#D55E00", "Pooled" = "#000000"))+
    ylab("") +
    ggtitle("")+
    xlab("")+
    theme_bw()+
    theme(panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(colour = "black"),
          axis.line.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          legend.position="none",
          strip.text.x=element_text(size=10,angle=0),
          strip.placement = "top",
          strip.background = element_rect(fill="transparent", 
                                          colour = "transparent"))+
  facet_wrap(measure ~ ., scales = "free")
```

phthalate
```{r, echo=FALSE, message=FALSE}
dt_phthalate<- st |> filter(group=="Phthalates")

phthalate_mean <- dt_phthalate |> 
  group_by(measure) |> 
  summarize(mean_val = mean(median))

phthalate<-ggplot(dt_phthalate, aes(y = as.factor(cohort), x = median, xmin = q25, xmax = q75)) + 
  geom_pointrange(aes(col = cohort), position=position_dodge(width=1),size = 1) +
    scale_color_manual(values = c("HOME" = "#0072B2", 
                                  "MIREC" = "#D55E00", "Pooled" = "#000000"))+
    ylab("") +
    ggtitle("")+
    xlab("")+
    theme_bw()+
    theme(panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(colour = "black"),
          axis.line.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          legend.position="none",
          strip.text.x=element_text(size=10,angle=0),
          strip.placement = "top",
          strip.background = element_rect(fill="transparent", 
                                          colour = "transparent"))+
  facet_wrap(measure ~ ., scales = "free")
```

op_pest
```{r, echo=FALSE, message=FALSE}
dt_op_pest<- st |> filter(group=="OP_pest")

op_pest_mean <- dt_op_pest |> 
  group_by(measure) |> 
  summarize(mean_val = mean(median))

op_pest<-ggplot(dt_op_pest, aes(y = as.factor(cohort), x = median, xmin = q25, xmax = q75)) + 
  geom_pointrange(aes(col = cohort), position=position_dodge(width=1),size = 1) +
    scale_color_manual(values = c("HOME" = "#0072B2", 
                                  "MIREC" = "#D55E00", "Pooled" = "#000000"))+
    ylab("") +
    ggtitle("")+
    xlab("")+
    theme_bw()+
    theme(panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(colour = "black"),
          axis.line.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          legend.position="none",
          strip.text.x=element_text(size=10,angle=0),
          strip.placement = "top",
          strip.background = element_rect(fill="transparent", 
                                          colour = "transparent"))+
  facet_wrap(measure ~ ., scales = "free")
```

outcome
```{r, echo=FALSE, message=FALSE}
dt_outcome<- st |> filter(group=="Outcome")

outcome_mean <- dt_outcome |> 
  group_by(measure) |> 
  summarize(mean_val = mean(median))

outcome<-ggplot(dt_outcome, aes(y = as.factor(cohort), x = median, xmin = q25, xmax = q75)) + 
  geom_pointrange(aes(col = cohort), position=position_dodge(width=1),size = 1) +
    scale_color_manual(values = c("HOME" = "#0072B2", 
                                  "MIREC" = "#D55E00", "Pooled" = "#000000"))+
    ylab("") +
    ggtitle("")+
    xlab("")+
    theme_bw()+
    theme(panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(colour = "black"),
          axis.line.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          legend.position="none",
          strip.text.x=element_text(size=10,angle=0),
          strip.placement = "top",
          strip.background = element_rect(fill="transparent", 
                                          colour = "transparent"))+
  facet_wrap(measure ~ ., scales = "free")
```

```{r, echo=FALSE, message=FALSE, fig.height=12, fig.width=12, dpi=300}
merged_plt<- plot_grid(metal, pops,pfas,
          paraben,opfr,tcs_bpa,
          op_pest,phthalate, outcome,
          labels = c("Metals (ng/ml)", "POPs (ng/g lipid)", 
                     "PFAS (ng/ml)", 
                     "Parabens (ng/ml)", "OPFR (ng/ml)", "TCS & BPA (ng/ml)",
                     "OP_Pesticides (ng/ml)", "Phthalates (ng/ml)", "WPPSI-Scale"),
          rel_widths = c(1.6,1.8,1.6,
                         1.6,1.8,1.6,
                         1.6,1.8,1.6),
          label_size = 10,
          nrow = 3,
          ncol = 3)

# extract a legend that is laid out horizontally
legend_b <- get_legend(paraben + 
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom"))

# add the legend underneath the row we made earlier. Give it 10%
# of the height of one plot (via rel_heights).
plot_grid(merged_plt, legend_b, ncol = 1, rel_heights = c(1, .05))

ggsave("E:/BBK17/pj/data_2023apr/results/iq_paper/summary.tiff",
       width=13, height= 10, dpi=300)
```




