---
title: "03.3_qgcomp"
author: "Jagadeesh Puvvula"
date: "2023-02-14"
output: pdf_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(janitor)
library(qgcomp)
```

```{r, echo=FALSE, message=FALSE}
dat<- read_csv("E:/BBK17/pj/wppsi_exp_out_comb/wppsi_fin.csv") |>
  mutate_if(is.numeric, round, 4) |>
  drop_na() |>
  clean_names() |>
  rename(Pb=pbsg, Hg=hgsg, DMA=dma_sg, DDE= dde_lp, PBDE_47 = pbde47_lp,
         PCB_118=pcb118_lp, PCB_138=pcb138_lp, PCB_153=pcb153_lp,
         PCB_180=pcb180_lp, PFHxS=pf_hx_spl, PFOA=pfoapl, PFOS=pfospl,
         BCEtP=bcetp_sg, BDCPP=bdcpp_sg, DBuP=dbup_sg, DPhP=dphp_sg,
         TCS=tcs_sg, BPA=bpa_sg, MBP=mbp_sg, MBZP=mbzp_sg, MCPP=mcpp_sg,
         sigma_DEHP=dehp, MEP=mep_sg, MIBP=mibp_sg, di_Ethyl_OP=op_de,
         di_Methyl_OP=op_dm, B_PB=b_pb, M_PB=m_pb, P_PB=p_pb)|>
  select(c(Pb, Hg, DMA, DDE, PBDE_47, PCB_118, PCB_138, PCB_153, PCB_180,
          PFHxS, PFOA, PFOS, BCEtP, BDCPP, DBuP, DPhP, TCS, BPA, MBP, MBZP,
          MCPP, sigma_DEHP, MEP, MIBP, di_Ethyl_OP, di_Methyl_OP, 
          B_PB, M_PB, P_PB, wppsi_fsiq, wppsi_viq, wppsi_piq, cohort, city,
          sex, race_bin, cotinine, mom_edu_cat, home_score_total, parity_n, mom_age)) 

dat<- dat |> 
  mutate(across(all_of(c("cohort", "city", "sex", "race_bin", 
                         "parity_n", "mom_edu_cat")), as.factor))
str(dat)
```

For gender stratified analysis
```{r}
dat<- dat |>
  filter(sex=="Female")|>
  select(-c(sex))
```


For 14 chemicals
```{r}
dat <- dat |>
  select(4,5,17,18,19,21,20,22,23,24,25,26,28:29,30:40) |>
  mutate_at(vars(1:14), log10) |>
  rename_with(~ paste0("log_", .x), 1:14)


mixture<- names(dat[c(1:14)])
```


WPPSI-FSIQ-ALL
```{r, echo=FALSE, message=FALSE, fig.height=12, fig.width=12, dpi=300}
#mixture<- names(dat[c(1:29)])

nb_gcomp_fit<- qgcomp.noboot(wppsi_fsiq ~ .,
                             expnms = mixture,
                             data = dat[-c(16,17)],
                             family= gaussian(), q=10)

nb_gcomp_fit
plot(nb_gcomp_fit)

save(nb_gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/nb_fsiq_all.rda")

gcomp_fit<- qgcomp.boot(wppsi_fsiq ~ .,
                        expnms = mixture,
                        data = dat[-c(16,17)],
                        family= gaussian(), q=10, B = 250,
                        seed = 2022)
gcomp_fit
plot(gcomp_fit)
save(gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/b_fsiq_all.rda")
```


WPPSI-VIQ-ALL
```{r, echo=FALSE, message=FALSE, fig.height=12, fig.width=12, dpi=300}
nb_gcomp_fit<- qgcomp.noboot(wppsi_viq ~ .,
                             expnms = mixture,
                             data = dat[-c(15,17)],
                             family= gaussian(), q=10)

nb_gcomp_fit
plot(nb_gcomp_fit)
save(nb_gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/nb_viq_all.rda")

gcomp_fit<- qgcomp.boot(wppsi_viq ~ .,
                        expnms = mixture,
                        data = dat[-c(15,17)],
                        family= gaussian(), q=10, B = 250,
                        seed = 2022)
gcomp_fit
plot(gcomp_fit)
save(gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/b_viq_all.rda")
```


WPPSI-PIQ-ALL
```{r, echo=FALSE, message=FALSE, fig.height=12, fig.width=12, dpi=300}

nb_gcomp_fit<- qgcomp.noboot(wppsi_piq ~ .,
                             expnms = mixture,
                             data = dat[-c(15,16)],
                             family= gaussian(), q=10)

nb_gcomp_fit
plot(nb_gcomp_fit)
save(nb_gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/nb_piq_all.rda")

gcomp_fit<- qgcomp.boot(wppsi_piq ~ .,
                        expnms = mixture,
                        data = dat[-c(15,16)],
                        family= gaussian(), q=10, B = 250,
                        seed = 2022)
gcomp_fit
plot(gcomp_fit)
save(gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/b_piq_all.rda")
```

WPPSI-FSIQ-HOME
```{r, echo=FALSE, message=FALSE, fig.height=12, fig.width=12, dpi=300}
dat_home<- dat |>
  filter(cohort=="1")|>
  select(-c(cohort, city))

nb_gcomp_fit<- qgcomp.noboot(wppsi_fsiq ~ .,
                             expnms = mixture,
                             data = dat_home[-c(16,17)],
                             family= gaussian(), q=10)

nb_gcomp_fit
plot(nb_gcomp_fit)
save(nb_gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/nb_fsiq_home.rda")

gcomp_fit<- qgcomp.boot(wppsi_fsiq ~ .,
                        expnms = mixture,
                        data = dat_home[-c(16,17)],
                        family= gaussian(), q=10, B = 250,
                        seed = 2022)
gcomp_fit
plot(gcomp_fit)
save(gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/b_fsiq_home.rda")
```


WPPSI-VIQ-HOME
```{r, echo=FALSE, message=FALSE, fig.height=12, fig.width=12, dpi=300}

nb_gcomp_fit<- qgcomp.noboot(wppsi_viq ~ .,
                             expnms = mixture,
                             data = dat_home[-c(15,17)],
                             family= gaussian(), q=10)

nb_gcomp_fit
plot(nb_gcomp_fit)
save(nb_gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/nb_viq_home.rda")

gcomp_fit<- qgcomp.boot(wppsi_viq ~ .,
                        expnms = mixture,
                        data = dat_home[-c(15,17)],
                        family= gaussian(), q=10, B = 250,
                        seed = 2022)
gcomp_fit
plot(gcomp_fit)
save(gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/b_viq_home.rda")
```


WPPSI-PIQ-HOME
```{r, echo=FALSE, message=FALSE, fig.height=12, fig.width=12, dpi=300}

nb_gcomp_fit<- qgcomp.noboot(wppsi_piq ~ .,
                             expnms = mixture,
                             data = dat_home[-c(15,16)],
                             family= gaussian(), q=10)

nb_gcomp_fit
plot(nb_gcomp_fit)
save(nb_gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/nb_piq_home.rda")

gcomp_fit<- qgcomp.boot(wppsi_piq ~ .,
                        expnms = mixture,
                        data = dat_home[-c(15,16)],
                        family= gaussian(), q=10, B = 250,
                        seed = 2022)
gcomp_fit
plot(gcomp_fit)
save(gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/b_piq_home.rda")
```

WPPSI-FSIQ-MIREC
```{r, echo=FALSE, message=FALSE, fig.height=12, fig.width=12, dpi=300}
dat_mirec<- dat |>
  filter(cohort=="2")|>
  select(-c(cohort))

nb_gcomp_fit<- qgcomp.noboot(wppsi_fsiq ~ .,
                             expnms = mixture,
                             data = dat_mirec[-c(16,17)],
                             family= gaussian(), q=10)

nb_gcomp_fit
plot(nb_gcomp_fit)
save(nb_gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/nb_fsiq_mirec.rda")

gcomp_fit<- qgcomp.boot(wppsi_fsiq ~ .,
                        expnms = mixture,
                        data = dat_mirec[-c(16,17)],
                        family= gaussian(), q=10, B = 250,
                        seed = 2022)
gcomp_fit
plot(gcomp_fit)
save(gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/b_fsiq_mirec.rda")
```


WPPSI-VIQ-MIREC
```{r, echo=FALSE, message=FALSE, fig.height=12, fig.width=12, dpi=300}

nb_gcomp_fit<- qgcomp.noboot(wppsi_viq ~ .,
                             expnms = mixture,
                             data = dat_mirec[-c(15,17)],
                             family= gaussian(), q=10)

nb_gcomp_fit
plot(nb_gcomp_fit)
save(nb_gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/nb_viq_mirec.rda")

gcomp_fit<- qgcomp.boot(wppsi_viq ~ .,
                        expnms = mixture,
                        data = dat_mirec[-c(15,17)],
                        family= gaussian(), q=10, B = 250,
                        seed = 2022)
gcomp_fit
plot(gcomp_fit)
save(gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/b_viq_mirec.rda")
```


WPPSI-PIQ-MIREC
```{r, echo=FALSE, message=FALSE, fig.height=12, fig.width=12, dpi=300}

nb_gcomp_fit<- qgcomp.noboot(wppsi_piq ~ .,
                             expnms = mixture,
                             data = dat_mirec[-c(15,16)],
                             family= gaussian(), q=10)

nb_gcomp_fit
plot(nb_gcomp_fit)
save(nb_gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/nb_piq_mirec.rda")

gcomp_fit<- qgcomp.boot(wppsi_piq ~ .,
                        expnms = mixture,
                        data = dat_mirec[-c(15,16)],
                        family= gaussian(), q=10, B = 250,
                        seed = 2022)
gcomp_fit
plot(gcomp_fit)
save(gcomp_fit, file = "E:/BBK17/pj/wppsi_results/qgcomp/b_piq_mirec.rda")
```


consolidated results
```{r, echo=FALSE, message=FALSE, fig.height=4, fig.width=6, dpi=300}
res<- read_csv("E:/BBK17/pj/wppsi_results/qgcomp/qgcomp_res.csv")

res$cohort<- factor(res$cohort, levels = c("pooled", "HOME", "MIREC"))

cbbPalette <- c("#D55E00", "#0072B2")

ggplot(res, aes(x = as.factor(model), y = beta, ymin = ll, ymax = ul)) + 
  geom_pointrange(aes(col = neg_beta, shape=bootstrap), 
                  position=position_dodge(width=0.5),size = 0.6) +
  geom_hline(aes(yintercept = 0), linetype="dashed") + 
  scale_colour_manual(values=cbbPalette) +
  scale_y_continuous(breaks = seq(-2.5,5.5,1.5))+
  labs(x=NULL,
       y=expression(paste(beta[q-gcomp]," [95% CI]")),
       title = "Joint association between prenatal chemical mixture during first trimester \nand child IQ",
       caption = "Pooled n=617; HOME-n=139; MIREC-n=478\n
       Effect estimates adjusted for cohort (for pooled only), city (for pooled and MIREC only), \nMom: serum cotinine, education, race, age, parity; Child: gender, HOME-score")+
  theme_bw()+
  theme(axis.line = element_line(colour = "black"))+
  theme(plot.caption = element_text(size = 6),
        plot.title=element_text(size = 11, hjust = 0),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        text=element_text(size=10),
        axis.text = element_text(size = 10),
        axis.text.x=element_text(size=10,angle=0),
        axis.ticks.x=element_blank(),
        strip.text.x=element_text(size=10,angle=0),
        strip.text.y = element_text(size=12),
        strip.placement = "outside",
        strip.background = element_rect(fill=NULL, colour = NULL),
        legend.box.just = "right",
        legend.spacing = unit(0, "cm"),
        legend.position = c(0.85,0.95),
        legend.box = "vertical",
        legend.direction = "horizontal",
        legend.text = element_text(size = 8),
        legend.key = element_blank(),
        legend.key.height = unit(3, "mm"))+
  facet_grid(.~cohort, scales = "free", switch = "x", space = "free_x")


ggsave("E:/BBK17/pj/wppsi_results/qgcomp/qgcomp_res.tiff", 
       width = 6,height = 4,
       dpi=300)
```


sensitivity testing
```{r}
dat_test <- dat |>
  select(4,5,17,18,19,21,20,22,23,24,25,26,28:29,30:41) |>
  mutate_at(vars(1:14), log10) |>
  rename_with(~ paste0("log_", .x), 1:14)


mixture<- names(dat_test[c(1:14)])

nb_gcomp_fit<- qgcomp.noboot(wppsi_fsiq ~ .,
                             expnms = mixture,
                             data = dat[-c(16,17)],
                             family= gaussian(), q=10)

nb_gcomp_fit


gcomp_fit<- qgcomp.boot(wppsi_piq ~ .,
                        expnms = mixture,
                        data = dat_test[-c(15,16)],
                        family= gaussian(), q=10, B = 250,
                        seed = 2022)
gcomp_fit
```

sensitivity plot
```{r}
res<- read_csv("E:/BBK17/pj/wppsi_results/qgcomp_14chem/qgcomp_prog_rep.csv")

res$cohort<- factor(res$cohort, levels = c("Pooled", "HOME", "MIREC"))

cbbPalette <- c("#D55E00", "#0072B2")

ggplot(res, aes(x = as.factor(model), y = beta, ymin = ll, ymax = ul)) + 
  geom_pointrange(aes(col = sign, shape=bootstrap), 
                  position=position_dodge(width=0.5),size = 0.6) +
  geom_hline(aes(yintercept = 0), linetype="dashed") + 
  scale_colour_manual(values=cbbPalette) +
  labs(x=NULL,
       y=expression(paste(beta[q-gcomp]," [95% CI]")),
       title = "Joint association between prenatal chemical mixture during first trimester and child IQ",
       caption = "Mixture includes 14 environmental chemicals: Triclosan, BPA, POPs (DDE,PBDE-47), Parabens (Methyl-paraben, Propyl-paraben), Phthalates (MBP, MBZP, MCPP, MEP, MIBP, Sigma-DEHP), OP-pesticides (Sigma-di-ethyl-op, Sigma-di-methyl-op)
       Effect estimates adjusted for cohort, city (for pooled), Maternal: serum cotinine, education, race, age, parity; Child: gender, HOME-score
       Effect estimates associated with every 10% increase in the mixture; For bootstrap, estimates generated using 250 random samples")+
  theme_bw()+
  theme(axis.line = element_line(colour = "black"))+
  theme(plot.caption = element_text(size = 6),
        plot.title=element_text(size = 11, hjust = 0),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        text=element_text(size=10),
        axis.text = element_text(size = 10),
        axis.text.x=element_text(size=10,angle=0),
        axis.ticks.x=element_blank(),
        strip.text.x=element_text(size=10,angle=0),
        strip.text.y = element_text(size=12),
        strip.placement = "outside",
        strip.background = element_rect(fill=NULL, colour = NULL),
        legend.box.just = "right",
        legend.spacing = unit(0, "cm"),
        legend.position = c(0.85,0.95),
        legend.box = "vertical",
        legend.direction = "horizontal",
        legend.text = element_text(size = 8),
        legend.key = element_blank(),
        legend.key.height = unit(3, "mm"))+
  facet_grid(gender~cohort, scales = "free", switch = "x", space = "free_x")


ggsave("E:/BBK17/pj/wppsi_results/qgcomp_14chem/qgcomp_prog_rep.tiff", 
       width = 12,height = 8,
       dpi=300)


```

