---
title: "03.3.1_qgcomp_interactions"
author: "Jagadeesh Puvvula"
date: "2023-09-11"
output: pdf_document
---

```{r, echo=FALSE, message=FALSE}

library(pacman)
pacman::p_load(tidyverse, janitor,qgcomp, qgcompint)
path <- "E:/BBK17/pj/data_2023apr/obs_w_outcome/"

dat<- read_csv(paste0(path, "wppsi_f_analy.csv"))
```


```{r, echo=FALSE, message=FALSE}
dat<- dat |>
  mutate_if(is.numeric, round, 4) |>
  clean_names() |>
  rename(Pb=pb, Hg=hg, DMA=dma, DDE= dde, PBDE_47 = pbde47,
         PCB_118=pcb118, PCB_138=pcb138, PCB_153=pcb153,
         PCB_180=pcb180, PFHxS=pfhxs, PFOA=pfoa, PFOS=pfos,
         BCEP=bcep, BDCIPP=bdcipp, DNBP=dnbp, DPhP=dphp,
         TCS=tcs, BPA=bpa, MBP=mbp, MBZP=mbzp, MCPP=mcpp,
         sigma_DEHP=dehp, MEP=mep, MIBP=mibp, di_Ethyl_OP=op_de,
         di_Methyl_OP=op_dm, B_PB=b_pb, M_PB=m_pb, P_PB=p_pb, city=center,
         mom_edu_cat=edu3)|>
  mutate(race_bin = ifelse(race == "white", 1, 2))|>
  mutate(sex = ifelse(sex == "1", "Male", "Female"))|>
  select(c(Pb, Hg, DMA, DDE, PBDE_47, PCB_118, PCB_138, PCB_153, PCB_180,
          PFHxS, PFOA, PFOS, BCEP, BDCIPP, DNBP, DPhP, TCS, BPA, MBP, MBZP,
          MCPP, sigma_DEHP, MEP, MIBP, di_Ethyl_OP, di_Methyl_OP, 
          B_PB, M_PB, P_PB, cotinine, home_score_total, mom_age, 
          cohort, city, sex, race_bin,  mom_edu_cat, parity_n, fish_int_pm,
          wppsi_fsiq, wppsi_viq, wppsi_piq))

dat<- dat |> 
  mutate(across(all_of(c("cohort", "city", "sex", "race_bin", 
                         "parity_n", "mom_edu_cat", "fish_int_pm")), as.factor))
```

for 29 chemicals
```{r}
# for all chemicals select 1:32
dat <- dat |>
  select(1:42) |>
  drop_na()|>
  mutate_at(vars(1:30), ~log10(.+0.0000001)) |>
  rename_with(~ paste0("log_", .x), 1:30) |>
  drop_na() |>
  as.data.frame()


mixture<- names(dat[c(1:29)])
```

```{r}
qgcomp_emm <- function(outcomes, data, output_folder, chemicals, covariates, q, b) {
  for(outcome in outcomes){
    formula <- as.formula(paste(outcome, chemicals,covariates))
    
    nb <- qgcomp.emm.noboot(formula, expnms = mixture, emmvar = "sex", data = data, 
                            family= gaussian(), q=q)
    boot <- qgcomp.emm.boot(formula, expnms = mixture, emmvar = "sex", data = data, 
                            family= gaussian(), q=q, B = b, seed = 2022)
    
    save(nb, file = paste0(output_folder, "/", "emm_nb",  "_", outcome, ".rda"))
    save(boot, file = paste0(output_folder, "/", "emm_boot", "_", outcome, ".rda"))
  }
  }
```

#interaction for 29 chemical mixture
```{r}
qgcomp_emm(outcomes = c("wppsi_fsiq", "wppsi_viq", "wppsi_piq"), 
            output_folder = "E:/BBK17/pj/data_2023apr/results/qgcomp_emm",
            chemicals = "~sex+log_Pb+log_Hg+log_DMA+log_DDE+log_PBDE_47+log_PCB_118+
            log_PCB_138+log_PCB_153+log_PCB_180+log_PFHxS+log_PFOA+log_PFOS+
            log_BCEP+log_BDCIPP+log_DNBP+log_DPhP+log_TCS+log_BPA+log_MBP+
            log_MBZP+log_MCPP+log_sigma_DEHP+log_MEP+log_MIBP+log_di_Ethyl_OP+
            log_di_Methyl_OP+log_B_PB+log_M_PB+log_P_PB+",
            covariates= "race_bin + log_cotinine +mom_edu_cat + home_score_total + parity_n + mom_age + cohort + city",
            #emm="sex",
            q=4,
            b=400,
            dat = dat)
```

#print interaction term slope and p-value
```{r}
load("E:/BBK17/pj/data_2023apr/results/qgcomp_emm/emm_nb_wppsi_piq.rda")

summary_data <- ls() %>%
  .[1] %>%
  get() %>%
  summary() %>%
  `[[`("coefficients") %>%
  `[`("psi3", )

sprintf("Estimate: %.2f (%.2f, %.2f), Pr(>|t|): %.2f",
                            round(summary_data["Estimate"], 2),
                            round(summary_data["Lower CI"], 2),
                            round(summary_data["Upper CI"], 2),
                            round(summary_data["Pr(>|t|)"], 2))

rm(list = ls())
```

