---
title: "03.4_gwqs"
author: "Jagadeesh Puvvula"
date: "2023-09-18"
output: pdf_document
---

```{r, echo=FALSE, message=FALSE}

library(pacman)
pacman::p_load(tidyverse, janitor, gWQS)
path <- "E:/BBK17/pj/data_2023apr/obs_w_outcome/"

dat<- read_csv(paste0(path, "wppsi_f_analy.csv"))
```


```{r, echo=FALSE, message=FALSE}
dat<- dat |>
  mutate_if(is.numeric, round, 4) |>
  clean_names() |>
  mutate(pb = if_else(cohort == "1", pb * 10, pb))|>
  rename(Pb=pb, Hg=hg, DMA=dma, DDE= dde, PBDE_47 = pbde47,
         PCB_118=pcb118, PCB_138=pcb138, PCB_153=pcb153,
         PCB_180=pcb180, PFHxS=pfhxs, PFOA=pfoa, PFOS=pfos,
         BCEtP=bcetp, BDCPP=bdcpp, DBuP=dbup, DPhP=dphp,
         TCS=tcs, BPA=bpa, MBP=mbp, MBZP=mbzp, MCPP=mcpp,
         sigma_DEHP=dehp, MEP=mep, MIBP=mibp, di_Ethyl_OP=op_de,
         di_Methyl_OP=op_dm, B_PB=b_pb, M_PB=m_pb, P_PB=p_pb, city=center,
         mom_edu_cat=edu3)|>
  mutate(race_bin = ifelse(race == "white", 1, 2))|>
  select(c(Pb, Hg, DMA, DDE, PBDE_47, PCB_118, PCB_138, PCB_153, PCB_180,
          PFHxS, PFOA, PFOS, BCEtP, BDCPP, DBuP, DPhP, TCS, BPA, MBP, MBZP,
          MCPP, sigma_DEHP, MEP, MIBP, di_Ethyl_OP, di_Methyl_OP, 
          B_PB, M_PB, P_PB, cotinine, home_score_total, mom_age, 
          cohort, city, sex, race_bin,  mom_edu_cat, parity_n, 
           wppsi_fsiq, wppsi_viq, wppsi_piq,)) 
```

for 29 chemicals
```{r}
# for all chemicals select 1:32
dat <- dat |>
  select(1:41) |>
  drop_na()|>
  mutate_at(vars(1:30), ~log10(.+0.0000001)) |>
  rename_with(~ paste0("log_", .x), 1:30) |>
  drop_na()


mixture<- names(dat)[1:29]
```

```{r}
wqs_func(outcomes = c("wppsi_fsiq", "wppsi_viq", "wppsi_piq"),
         dat=dat,
         output_folder = "E:/BBK17/pj/data_2023apr/results/wqs",
         covariates = c("log_cotinine", "home_score_total", "mom_age",
                        "race_bin", "mom_edu_cat", "parity_n"),
         include_sex = T, include_cohort = T,
         b1_pos = FALSE, b1_constr = TRUE,
         rh=100)
```

```{r}
nb_fsiq_neg <- gwqs(wppsi_fsiq ~ wqs+log_cotinine+home_score_total+mom_age+mom_edu_cat+parity_n+race_bin, 
                 mix_name = mixture, q=4,
                 data = dat, validation = 0.6, b=100, b1_pos = F,b1_constr = F,
                 family = "gaussian", seed = 2023)
```

```{r}
load("E:/BBK17/pj/data_2023apr/results/wqs/wqsrh_male_cohort_HOME_wppsi_fsiq.rda")
```

gwqs_summary_tab(wqsrh)


