---
title: "03.5.1_bkmr-all"
author: "Jagadeesh Puvvula"
date: "2023-02-20"
output: pdf_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(janitor)
library(bkmr)
library(Matrix)
library(fields)
library(bindrcpp)
```

```{r, echo=FALSE, message=FALSE}
dat<- read_csv("E:/BBK17/pj/wppsi_exp_out_comb/wppsi_fin.csv") |>
  mutate_if(is.numeric, round, 4) |>
  drop_na() |>
  clean_names() |>
  mutate(race_bin = if_else(sex=="Male", 1, 2))|>
  rename(Pb=pbsg, Hg=hgsg, DMA=dma_sg, DDE= dde_lp, PBDE_47 = pbde47_lp,
         PCB_118=pcb118_lp, PCB_138=pcb138_lp, PCB_153=pcb153_lp,
         PCB_180=pcb180_lp, PFHxS=pf_hx_spl, PFOA=pfoapl, PFOS=pfospl,
         BCEtP=bcetp_sg, BDCPP=bdcpp_sg, DBuP=dbup_sg, DPhP=dphp_sg,
         TCS=tcs_sg, BPA=bpa_sg, MBP=mbp_sg, MBZP=mbzp_sg, MCPP=mcpp_sg,
         sigma_DEHP=dehp, MEP=mep_sg, MIBP=mibp_sg, di_Ethyl_OP=op_de,
         di_Methyl_OP=op_dm, B_PB=b_pb, M_PB=m_pb, P_PB=p_pb)|>
  select(c(Pb, Hg, DMA, DDE, PBDE_47, PCB_118, PCB_138, PCB_153, PCB_180,
          PFHxS, PFOA, PFOS, BCEtP, BDCPP, DBuP, DPhP, TCS, BPA, MBP, MBZP,
          MCPP, sigma_DEHP, MEP, MIBP, di_Ethyl_OP, di_Methyl_OP, 
          B_PB, M_PB, P_PB, wppsi_fsiq, wppsi_viq, wppsi_piq, cohort, city,
          race_bin, cotinine, mom_edu_cat, home_score_total, parity_n, mom_age)) 

```


```{r, echo=FALSE, message=FALSE}
#Creating mixture variable matrix
mixture<- with(dat, cbind(Pb, Hg, DMA, DDE, PBDE_47, PCB_118, PCB_138, 
                                PCB_153, PCB_180,PFHxS, PFOA, PFOS, BCEtP, 
                                BDCPP, DBuP, DPhP, TCS, BPA, MBP, MBZP,MCPP, 
                                sigma_DEHP, MEP, MIBP, di_Ethyl_OP, di_Methyl_OP, 
                                B_PB, M_PB, P_PB))

# log 10 conversion of exposure variables
ln_mixture <- apply(mixture, 2, log10)

# log conversion and scale outcomes
wppsi_fsiq<- dat$wppsi_fsiq
wppsi_viq<- dat$wppsi_viq
wppsi_piq<- dat$wppsi_piq

#  scale continuous covariates
covariates<- with(dat, cbind(cohort, race_bin, mom_edu_cat,cotinine,
                             home_score_total, parity_n, mom_age))
```

=================================================================================
FSIQ
```{r}
set.seed(2023)
knots100 <- fields::cover.design(ln_mixture, nd=100)$design

set.seed(2023)
fsiq_all<- kmbayes(y= wppsi_fsiq, Z=ln_mixture, X=covariates,
              iter = 100000, verbose = T,  varsel = T,
              groups = c(1,1,1,2,2,2,2,2,2,3,3,3,
                         4,4,4,4,5,5,6,6,6,6,6,6,
                         7,7,8,8,8),
              knots=knots100)

summary(fsiq_all)

#for PIPs
ExtractPIPs(fsiq_all)

######### PLOTTING ##################
modeltoplot <- fsiq_all
modeltoplot.name <- "wppsi_mod"
plot.name <- "model"
Z <- ln_mixture

sel <- seq(12501, 25000, by =50)
##############
TracePlot(fit=modeltoplot, par = "beta", sel = sel)
TracePlot(fit = modeltoplot, par = "sigsq.eps", sel= sel)

##################
pred.resp.univar <- PredictorResponseUnivar(fit = modeltoplot, sel=sel, method="approx")
pred.resp.bivar  <- PredictorResponseBivar(fit = modeltoplot,  min.plot.dist = 1, sel=sel, method="approx")
pred.resp.bivar.levels <- PredictorResponseBivarLevels(pred.resp.df = pred.resp.bivar, Z = Z,
                                                       both_pairs = TRUE, qs = c(0.25, 0.5, 0.75))

risks.overall <- OverallRiskSummaries(fit = modeltoplot, qs = seq(0.25, 0.75, 
                                                                  by = 0.05), 
                                      q.fixed = 0.5, method = "approx",sel=sel)

risks.singvar <- SingVarRiskSummaries(fit = modeltoplot, qs.diff = c(0.25, 0.75),
                                      q.fixed = c(0.25, 0.50, 0.75), method = "approx")

risks.int <- SingVarIntSummaries(fit = modeltoplot, qs.diff = c(0.25, 0.75), qs.fixed = c(0.25, 0.75))

save(fsiq_all, file = "E:/BBK17/pj/wppsi_results/bkmr/all/fsiq_all.rda")
```

=================================================================================
VIQ
```{r}
set.seed(2023)
knots100 <- fields::cover.design(ln_mixture_z, nd=100)$design

viq_all<- kmbayes(y= wppsi_viq, Z=ln_mixture_z, X=covariates,
              iter = 100000, verbose = T,  varsel = T,
              groups = c(1,1,1,2,2,2,2,2,2,3,3,3,
                         4,4,4,4,5,5,6,6,6,6,6,6,
                         7,7,8,8,8), 
              knots=knots100)

summary(viq_all)

#for PIPs
ExtractPIPs(viq_all)

######### PLOTTING ##################
modeltoplot <- viq_all
modeltoplot.name <- "viq_all"
plot.name <- "model"
Z <- ln_mixture_z

sel <- seq(12501, 25000, by =50)
##############
TracePlot(fit=modeltoplot, par = "beta", sel = sel)
TracePlot(fit = modeltoplot, par = "sigsq.eps", sel= sel)

save(viq_all, file = "E:/BBK17/pj/wppsi_results/bkmr/all/viq_all.rda")
```

=================================================================================
PIQ
```{r}
set.seed(2023)
knots100 <- fields::cover.design(ln_mixture_z, nd=100)$design

piq_all<- kmbayes(y= wppsi_piq, Z=ln_mixture_z, X=covariates,
              iter = 100000, verbose = T,  varsel = T,
              groups = c(1,1,1,2,2,2,2,2,2,3,3,3,
                         4,4,4,4,5,5,6,6,6,6,6,6,
                         7,7,8,8,8), 
              knots=knots100)

summary(piq_all)

#for PIPs
ExtractPIPs(piq_all)

######### PLOTTING ##################
modeltoplot <- piq_all
modeltoplot.name <- "piq_all"
plot.name <- "model"
Z <- ln_mixture_z

sel <- seq(12501, 25000, by =50)
##############
TracePlot(fit=modeltoplot, par = "beta", sel = sel)
TracePlot(fit = modeltoplot, par = "sigsq.eps", sel= sel)

save(viq_all, file = "E:/BBK17/pj/wppsi_results/bkmr/all/piq_all.rda")
```

