---
title: "associations"
author: "Puvvula"
date: "2022-11-03"
output: pdf_document
---

```{r}
#exposure
library(tidyverse)

dat<- read_csv("/Users/jpuvvula/Documents/data/home_16w_imp/mirec_transf/home_exp_fin.csv") |>
  pivot_wider(names_from = analyte, values_from = conc)

# variable 18 for DMA
dat<- dat[c(1,3,5,7,8,10,11,13,15,17,19,21,23,24,26,28,30,32,34,36,38,40,41:50,52)] 

#outcome
dat_out<- read_csv("/Users/jpuvvula/Documents/data/home_16w_imp/mirec_transf/outcome_wide.csv") |>
  select(names(dat_out[c(1:3)])) |>
  drop_na()

#analytic dataset
dat_fin<- inner_join(dat, dat_out, by="subject_id") |>
  drop_na()

#### FINAL ANALYTIC DATASET
write_csv(dat_fin, "/Users/jpuvvula/Documents/data_ver_jan04_2023/dat.csv")

#wide to long for summary table

dat_wide <- dat_fin |> 
  pivot_longer(!subject_id,
               names_to = "measure", values_to = "value")
dat_summ<- dat_wide |> 
    group_by(measure) |>
    summarise(geometric_mean = geomean(value), geometric_SD = geosd(value),
              arithmatic_mean=mean((value), na.rm=T), arithmatic_std=sd((value), na.rm = T),
              median = median((value), na.rm = T), q25 = quantile(value, .25, na.rm=T),
              q75 = quantile(value, .75, na.rm=T)) |>
    mutate_if(is.numeric, round, 3)
```

Generalized weighted quantile sum regression
```{r}
library(gWQS)

mixture<- names(dat_fin[(2:33)])

wqs_rh<- gwqsrh(bayley_men_mdi ~ wqs,
                    mix_name=mixture,
                    data=dat_fin,
                    q=10, validation=0.6,b=100,b1_pos = F,b1_constr = F,
                    family="gaussian",zilink = log, seed=2022,rh=10)

gwqs_summary_tab(wqs_rh)
gwqsrh_boxplot(wqs_rh, tau = 0.01)
gwqs_weights_tab(wqs_rh)


####### MIREC #########

mixture<- names(wppsi_fin[(8:39)])

wqs_rh<- gwqsrh(fsiq ~ wqs,
                    mix_name=mixture,
                    data=wppsi_fin,
                    q=10, validation=0.6,b=100,b1_pos = F,b1_constr = F,
                    family="gaussian",zilink = log, seed=2022,rh=10)

gwqs_summary_tab(wqs_rh)
gwqsrh_boxplot(wqs_rh, tau = 0.01)
gwqs_weights_tab(wqs_rh)

```

quantile g-computation
```{r}
library(qgcomp)

nb_gcomp_fit<- qgcomp.noboot(bayley_men_mdi ~ . ,
                        expnms = mixture,
                        data = dat_fin,
                        family= gaussian(), q=10)


gcomp_fit<- qgcomp.boot(bayley_men_mdi ~ . ,
                        expnms = mixture,
                        data = dat_fin,
                        family= gaussian(), q=10, B = 250,
                        seed = 2022)

plot(gcomp_fit)

###### MIREC ##########
gcomp_fit<- qgcomp.boot(fsiq ~ . ,
                        expnms = mixture,
                        data = wppsi_fin,
                        family= gaussian(), q=10, B = 250,
                        seed = 2022)

plot(gcomp_fit)


```

Bayesian Kernel machine regression
```{r}
library(bkmr)
library(Matrix)
library(fields)
library(bindrcpp)

#log conversion and scaling outcome

wppsi_fsiq_z <- scale(log(wppsi_fin$fsiq))

#Creating mixture variable matrix
mixture<- with(wppsi_fin, cbind(bcetp_sg, bdcpp_sg, bpa_sg, cotinine_sg,
                                dbup_sg, dde_lp,dep_sg, detp_sg, dma_sg,
                                dmp_sg, dmtp_sg, dphp_sg, HGSG, mbp_sg,
                                mbzp_sg, mcpp_sg, mehhp_sg, mehp_sg, meohp_sg,
                                mep_sg, mibp_sg, pbde153_lp, pbde47_lp, PBSG,
                                pcb118_lp, pcb138_lp, pcb153_lp, pcb180_lp,
                                PFHxSPL, PFOAPL, PFOSPL, tcs_sg))
 
# log conversion and scaling exposure variables
ln_mixture <- apply(mixture, 2, log) 
ln_mixture_z <- scale(ln_mixture) 

##### MODEL BUILDING #########
set.seed(2023)

knots100 <- fields::cover.design(ln_mixture_z, nd=100)$design
 
mod<- kmbayes(y= wppsi_fsiq_z, Z=ln_mixture_z, iter = 10000, verbose = T,  varsel = T,
              groups = c(1, 1, 2, 3, 1, 4,5, 5, 6, 5, 5, 1, 6, 7, 7, 7, 7, 7, 7,
                         7, 7, 4, 4, 6, 4, 4, 4, 4, 8, 8, 8, 9),
              knots=knots100)
 
summary(mod)
 
#for PIPs
ExtractPIPs(mod)

######### PLOTTING ##################
modeltoplot <- mod
 
modeltoplot.name <- "mod"
 
plot.name <- "model"
 
Z <- ln_mixture_z
 
sel <- seq(1251, 2500, by =50)
 
##############
 
TracePlot(fit=modeltoplot, par = "beta", sel = sel)
 
TracePlot(fit = modeltoplot, par = "sigsq.eps", sel= sel)
 
save(mod, file = "E://BBK17//pj//bkmr//bkmr_test.rda")
```




