---
title: "mirec_data"
author: "puvvula"
date: "2022-10-05"
output: pdf_document
---

```{r}

library(tidyverse)
library(readxl)
library(janitor)
library(skimr)
library(reshape2)
```

Outcome: child 3 Yr scores
```{r}
#parent: SRS-2
#child: NEPSY, and WPPSI-3

dat<-  read_csv("E:/BBK17/1. BBK17_June10 2022/CRF/2. MIREC-CD Plus STUDY/Data/NDEV.csv") |> clean_names() 
wppsi<- dat[c(1,2,11,13:48)] |>
  as.numeric(c(3:35))


dt_out<- read_excel("E://BBK17//1. BBK17_June10 2022//DV//2. MIREC-CD Plus STUDY//BBK17_CDPlus_BABY_DVs.xlsx") |> clean_names() 

#123 observations with missing all outcomes 
skim(dt_out)

#select relevant variables and rename join field
out_1 <- dt_out[c(1,4:45)] |> 
  rename(id_join=subject_id)

```


First trimester - Exposure
```{r}
#BPA triclosan (removing not reported records)
dat<- read_csv2("E://BBK17//1. BBK17_June10 2022//LAB/MIREC_RESEARCHERS RESULTS table_code 001//QueryData_code001.csv") |>
  clean_names() |>
  rename(tests_results_raw_result =researcher_results_raw_result) |>
  filter(complete.cases(researcher_results_unit_set))

dat$tests_results_test_name<- str_extract(dat$researcher_results_test_name, "^.{3}")

dat$tests_results_raw_result<-as.numeric(dat$tests_results_raw_result)

labres <- dat |> 
  group_by(specimen_bar_code, tests_results_test_name) |>
  summarise_at(vars("tests_results_raw_result"), sum)

labres<- labres |> mutate(flg_lod = case_when((
  tests_results_test_name=="BPA" & tests_results_raw_result<0.11) ~ "1",
  (tests_results_test_name=="BPA" & tests_results_raw_result>=0.11) ~ "0",
  (tests_results_test_name=="TRI" & tests_results_raw_result<0.12) ~ "1",
  (tests_results_test_name=="TRI" & tests_results_raw_result>=0.12) ~ "0")) |>
  filter(complete.cases(flg_lod))
  

dat$tests_results_test_name<- str_extract(dat$researcher_results_test_name, "^.{3}")

labres <- dat |> 
  group_by(specimen_bar_code, tests_results_test_name) |>
  summarise_at(vars("tests_results_raw_result"), sum)

x<-labres |> group_by(tests_results_test_name, flg_lod) |>
  summarise(tested=n())



#Phthalates
labres<- read_csv2("E://BBK17/2. BBK17_pending lab tests_July19 2022//LAB//MIREC_MICROALIQOUT RESULTS table code 001-01.001-03//QueryData_code 001-01.csv") |>
  clean_names()|>
  rename(tests_results_test_name = micro_aliquot_tests_results_test_name,
         tests_results_raw_result =micro_aliquot_tests_results_raw_result)

#Urine Arsenic, OP pesticides, OPFR Specific gravity, 
df_1 <-read_csv2("E://BBK17//1. BBK17_June10 2022//LAB//MIREC_TEST RESULTS table_codes 001.002.009.013.016.049.054.060.096.097.101//QueryData_code001.csv") |>
  clean_names() |> 
  mutate(id_join = str_sub(specimen_bar_code, 1,6))

df_1a <- df_1[c(5,6,10)] |> 
  pivot_wider(names_from = c(tests_results_test_name),
              values_from = tests_results_raw_result) 

num<- names(df_1a[c(2:15)])
df_1a[num]<- sapply(df_1a[num], as.numeric)

write_csv(df_1a, "E://BBK17//pj//pj_dat//ex_dat6.csv")

#Urine: Phthalates
df_2 <-read_csv2("E://BBK17//1. BBK17_June10 2022//LAB//MIREC_TEST RESULTS table_codes 001.002.009.013.016.049.054.060.096.097.101//QueryData_code002.csv") 

#Urine: Creatinine
df_6 <-read_csv2("E://BBK17//1. BBK17_June10 2022//LAB//MIREC_TEST RESULTS table_codes 001.002.009.013.016.049.054.060.096.097.101//QueryData_code049.csv") |> clean_names()

#Plasma: PBDE, PCB, OC Pesticides
df_3 <-read_csv2("E://BBK17//1. BBK17_June10 2022//LAB//MIREC_TEST RESULTS table_codes 001.002.009.013.016.049.054.060.096.097.101//QueryData_code009.csv") |> clean_names()

#Plasma: Tobacco and PFCs
df_4 <-read_csv2("E://BBK17//1. BBK17_June10 2022//LAB//MIREC_TEST RESULTS table_codes 001.002.009.013.016.049.054.060.096.097.101//QueryData_code013.csv") |> clean_names()

#Whole Blood: - metals
df_5 <-read_csv2("E://BBK17//1. BBK17_June10 2022//LAB//MIREC_TEST RESULTS table_codes 001.002.009.013.016.049.054.060.096.097.101//QueryData_code016.csv") |> clean_names()


#OPFR
labres<- read_csv2("E://BBK17/2. BBK17_pending lab tests_July19 2022//LAB//MIREC_MICROALIQOUT RESULTS table code 001-01.001-03//QueryData_code001-03.csv") |>
    clean_names()|>
    rename(tests_results_test_name = micro_aliquot_tests_results_test_name,
           tests_results_raw_result =micro_aliquot_tests_results_raw_result)

```

Creatinine adjustment = analyte concentration / creatinine concentration
lipid adjustment = (analyte concentration / lipid level)*102.6

```{r}
cre<- read_csv("E://BBK17/pj//imputed_data//CRE.csv")
cre$join_id<- str_extract(cre$subject_id,  "^.{8}")

dt<- read_csv("E://BBK17/pj//imputed_data//DMTPUR.csv") 
dt$join_id<- str_extract(dt$subject_id,  "^.{8}")
dat<- inner_join(dt,cre, by="join_id")

dat$dmtp_cr <- (dat$result.res.x/dat$result.res.y)
dat<- dat[c(1,2,10)] |> rename(dmtp = result.res.x) |>
  pivot_longer(!subject_id.x, names_to = "analyte", values_to = "conc")

write_csv(dat, "E://BBK17/pj//imputed_data//cre_adj//dmtp.csv")

############ for DDE, PBDE, PCB, PFAS ############
lipi<-  read_csv("E://BBK17/pj//imputed_data//LIPIPL.csv") 
lipi$join_id<- str_extract(lipi$subject_id,  "^.{8}") 

dt <- read_csv("E://BBK17/pj//imputed_data//PFOSPL.csv") 
dt$join_id<- str_extract(dt$subject_id,  "^.{8}")
dat<- inner_join(dt,lipi, by="join_id")
 
dat$pfos_lp <- (dat$result.res.x/dat$result.res.y)*102.6
dat<- dat[c(1,2,10)] |> rename(pfos = result.res.x) |>
  pivot_longer(!subject_id.x, names_to = "analyte", values_to = "conc")

write_csv(dat, "E://BBK17/pj//imputed_data//lipi_adj//pfos.csv")

```



Join exposure and cotinine, creatinine data
```{r}
df_1<- read_csv("E://BBK17//pj//pj_dat//ex_dat1.csv")
df_2<- read_csv("E://BBK17//pj//pj_dat//ex_dat2.csv")
df_3<- read_csv("E://BBK17//pj//pj_dat//ex_dat3.csv")
df_4<- read_csv("E://BBK17//pj//pj_dat//ex_dat4.csv")
df_5<- read_csv("E://BBK17//pj//pj_dat//ex_dat5.csv")
df_6<- read_csv("E://BBK17//pj//pj_dat//ex_dat6.csv")


x<- df_1 |> 
  full_join(df_2, by="id_join") |> 
  full_join(df_3, by="id_join") |> 
  full_join(df_4, by="id_join") |> 
  full_join(df_5, by="id_join") |> 
  full_join(df_6, by="id_join") 
  
#all exposures - Visit 3 year 
write_csv(x, "E://BBK17//pj//pj_dat//exp_all.csv")
```


join 1 trimester exposure with child 3-yr outcome
```{r}
exp<- read_csv("E://BBK17//pj//pj_dat//exp_all.csv")

mirec_full<- exp |> full_join(out_1, by="id_join")


```

correlation matrix
```{r}
#filter variables that has vales for at least 50% observations
var_names<- sapply(colnames(mirec_full), function(x) sum(is.na(mirec_full[x])) 
             < nrow(mirec_full)/2)

#subset of 34 out of 114 variables
df<- mirec_full[colnames(mirec_full)[var_names]]
write_csv(df, "E://BBK17//pj//pj_dat//corr.csv")

#load corr dataset for building correlation matrix
df<- read_csv("E://BBK17//pj//pj_dat//corr.csv")

#exclude ID variable 
cormat<- round(x=cor(df[2:34], method = "spearman", 
                     use= "complete.obs"), digits=2) |>
  melt() |> clean_names()

ggplot(cormat, aes(x=var1, y=var2, fill=value)) +
  geom_tile(color="white")+
  scale_fill_gradient(limit=c(-1,1), space= "Lab",
                      name="Spearman\nCorrelation")+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 10, hjust = 1))


```

```{r}
library(heatmaply)

heatmaply_cor(x=cor(df[2:34], method = "spearman", 
                     use= "complete.obs"),
              xlab = "Features",
              ylab = "Features",
              k_col = 2,
              k_row = 2)
ggsave("E://BBK17//pj//pj_dat//corplot.tiff",width=10,dpi=300)

```



